services:
  card-prediction:
    container_name: card-prediction-app
    image: card-prediction:latest
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]