services:
  card-prediction:
    container_name: card-prediction-app
    image: card-prediction:latest
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
    restart: unless-stopped
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
      - TF_ENABLE_ONEDNN_OPTS=0